author: Chris Ever

keywords: Hexo, Theme-AD

description: 子飞的网络日志

# 导航栏头部名称
nav_name: 子飞的网络日志

# 导航栏座右铭
motto: "既为朽木，当曝露于荒野"

github: "https://github.com/chirsz-ever/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件
custom_styles: 

# 自定义脚本文件
custom_scripts: 

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "night blue"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "商子飞"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">CC BY-NC-SA 4.0</a> 许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-08-13"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp-gzGzoHsz # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd # 填写您的appkey
  comment: false # 是否开启评论系统
  count: false # 是否开启文章统计

# 需要保证leancloud.count为true
welcome: 
  enable: false
  interval: 30

# 需要保证leancloud.comment为false
disqus: 
  enable: false
  id: 

# 需要保证leancloud.count为false
busuanzi: false

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - efe07af7441da2b69c4a41e42e73be4db47f66010a56900788a458354a7373ec # godbmw

share:
  twitter: false
  facebook: false
  weibo: false
  qq: false
  wechat: false

analytics:
  baidu:
    enable: true
  google:
    enable: true
    id: 
  "360":
    enable: true
    id: 

# 打赏图片
reward: false

# 第三方库的CDN地址
# 请根据情况自行决定是否替换为国内CDN
cdn: 
  leancloud: "//cdn.jsdelivr.net/npm/leancloud-storage@3.11.1/dist/av-min.js"
  mathjax: "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
  valine: "//unpkg.com/valine/dist/Valine.min.js"
  busuanzi: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
  font_awesome: "//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"

nav:
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  -
    name: "关于"
    path: "/about/"

footer:
  - 
    title: "博客推荐"
    children:
      - 
        name: "Matrix67: The Aha Moments"
        path: "http://www.matrix67.com/blog/"
      - 
        name: "GodBMW"
        path: "https://godbmw.com/"
      - 
        name: "阮一峰的个人网站"
        path: "http://ruanyifeng.com/"
  -
    title: "我的其他帐号"
    children: 
      -
        name: "知乎"
        path: "https://www.zhihu.com/people/chirsz-ever"
      -
        name: "百度贴吧"
        path: "http://tieba.baidu.com/home/main?id=11b5e8a2abe5ad90e9a39ee4ba86329821"

footer_contact: "Email: chirsz@foxmail.com"

friends_avatar_cdn: 
friends:
  -
    nickname: GodBMW
    avatar: /images/friends/godbmw.jpeg
    site: https://godbmw.com/
    meta: 主题作者
    show: true